name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip setuptools
          pip install cibuildwheel

      - name: Build Wheels
        env:
          CIBW_SKIP: "cp3*-win* *-i686 cp36-* cp37-* pp36-* pp37-* cp38-* pp38-* cp39-* pp39-*"
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: universal2
        run: cibuildwheel --output-dir dist

      - name: Build Source Distribution
        run: python setup.py sdist --dist-dir dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1